[tool.poetry]
name = "capstone-project"
version = "0.1.0"
description = "Data-driven software security metrics"
authors = ["Samuel Gamelin <samuel.gamelin@carleton.ca>", "John Breton <john.breton@carleton.ca>", "Mohamed Radwan <mohamed.radwan@carleton.ca>", "Khalil Aalab <Khalil.Aaalab@carleton.ca>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
